### ISSUE TITLE
Question about Landmarking Tool

### ISSUE THREAD

**Issue by dcnhan** [unibas-gravis/basel-face-pipeline#4]
Hi,

I would like to ask how I can obtain the landmark in case I want to align other 3D data to BMF reference model. Could you provide some more info about landmarking tool/ GUI that you use to obtain the landmarks?

Thanks

**Comment by BernhardEgger** [comment]
Hi dcnhan,

scalismo ui can do that.
https://github.com/unibas-gravis/scalismo-ui

There is special tool used for teaching which also comes with the landmark clicking ability:
http://shapemodelling.cs.unibas.ch/
If you are interested in that the easiest way would probably be to join the course on futurelearn which just starts this week.

Please use our google groups for questions
https://groups.google.com/forum/#!forum/scalismo
https://groups.google.com/forum/#!forum/scalismo-faces

Best
Bernhard
