### ISSUE TITLE
is there any differents between BFM09 and BFM17 ?

### ISSUE THREAD

**Issue by VincentXWD** [unibas-gravis/basel-face-pipeline#5]
is there any differents between BFM09 and BFM17 ?

**Comment by BernhardEgger** [comment]
Yes,
an improved age distribution, more precise registration and facial expressions
See the paper for details: https://gravis.dmi.unibas.ch/publications/2018/2018_Gerig_FG18.pdf

**Comment by VincentXWD** [comment]
I mean whether  I can use BFM17 through a BFM09 protocol or not.

**Comment by BernhardEgger** [comment]
Sorry I don't understand the question. Is there a specific software you are using?
Are you currently using the BMF09 or 17?
If you are using the 09 version, are you using the h5 file or a matlab file?
